services:
    web:
        build:
            context: ./docker/php
            args:
                WWWUSER: "${WWWUSER:-1000}"
                WWWGROUP: "${WWWGROUP:-1000}"
        volumes:
            - ./:/var/www/html
        ports:
            - ${HTTP_FORWARD_PORT:-8080}:80
        depends_on:
            - postgres
    postgres:
        image: pgvector/pgvector:pg16
        volumes:
            - db:/var/lib/postgres
        ports:
            - ${DB_FORWARD_PORT:-5432}:5432
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
    postgres-test:
        image: pgvector/pgvector:pg16
        ports:
            - ${DB_FORWARD_PORT:-5433}:5432
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - ${MAILHOG_SMTP_PORT:-1025}:1025
            - ${MAILHOG_WEB_PORT:-8025}:8025
volumes:
    db:
